### ISSUE TITLE
Support for Langdale and Dunfell

### ISSUE THREAD

**Issue by mikehaller** [eclipse-kanto/meta-kanto#46]
Great to see a Yocto layer for Kanto supporting the Kirkstone LTS release.

It would be great if meta-kanto would also be compatible with the current Dunfell LTS release, as many existing device manufacturers tend to have not yet updated.

Also preparing for the next LTS (Langdale) would be good.

**Tasks**
- #47 
- #48

**Comment by e-grigorov** [comment]
LTS support is always a great idea because it improves the project adoption. Just a small correction, accoring to [the official documentation](https://wiki.yoctoproject.org/wiki/Releases), LTS versions are:
- Kirkstone (4.0)
- Dunfell (3.1)

Most probably, the next LTS will be 5.X, not Langdale (4.1).

In any case, the current support will be extended with:
- a new branch for Dunfell as it's implemented for Kirkstone
- the main branch will be updated (if required) to support Langdate

**Comment by hristobojilov** [comment]
The problem is that dunfell uses go 1.14.15 for building of recipes but we need at least 1.17.
Poky manipulates PATH environment variable and if another version version of go is present there it cannot be used.
I haven't found a way to replace go toolchain used by poky.

**Comment by k-gostev** [comment]
I guess everything is done here.
